# Generated by Django 4.0.4 on 2022-05-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=150, null=True)),
                ('bairro', models.CharField(max_length=150, null=True)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
    ]
