# Generated by Django 4.0.4 on 2022-05-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='endereco',
            new_name='cidade',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
