# Generated by Django 4.0.4 on 2022-05-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_rename_endereco_endereco_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
