# Generated by Django 4.0.4 on 2022-05-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=150)),
                ('cpf_ou_cnpj', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('PESSOA_FISICA', 'Pessoa física'), ('PESSOA_JURIDICA', 'Pessoa jurídica')], max_length=15)),
            ],
        ),
    ]
